# action.yml
name: "QCVE - Code Scanning Sample"
description: "Run CodeQL Query against Public Project Databases"

inputs:
  username:
    description: 'Username'
    required: true
  query:
    description: 'Query path'
    required: true
  report:
    description: 'Report path'
    required: true
  database:
    description: 'Database'
    required: true
  number:
    description: 'Request Number'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.query }}
    - ${{ inputs.report }}
    - ${{ inputs.database }}
    - ${{ inputs.number }}